
import React from 'react';
import { ThemeType, Language, AppTheme } from './types';

export const THEMES: Record<ThemeType, AppTheme> = {
  [ThemeType.PinkSoft]: {
    bg: 'bg-pink-50',
    card: 'bg-white',
    text: 'text-pink-900',
    accent: 'bg-pink-500',
    border: 'border-pink-100',
    secondaryText: 'text-pink-600',
  },
  [ThemeType.BlueSky]: {
    bg: 'bg-sky-50',
    card: 'bg-white',
    text: 'text-sky-900',
    accent: 'bg-sky-500',
    border: 'border-sky-100',
    secondaryText: 'text-sky-600',
  },
  [ThemeType.MidnightBlue]: {
    bg: 'bg-slate-950',
    card: 'bg-slate-900',
    text: 'text-slate-100',
    accent: 'bg-indigo-600',
    border: 'border-slate-800',
    secondaryText: 'text-slate-400',
  },
  [ThemeType.MaroonMahony]: {
    bg: 'bg-red-950',
    card: 'bg-stone-900',
    text: 'text-red-50',
    accent: 'bg-red-700',
    border: 'border-stone-800',
    secondaryText: 'text-red-300',
  },
  [ThemeType.ChocolateCaramel]: {
    bg: 'bg-orange-950',
    card: 'bg-stone-900',
    text: 'text-orange-50',
    accent: 'bg-orange-700',
    border: 'border-stone-800',
    secondaryText: 'text-orange-300',
  }
};

export const TRANSLATIONS = {
  [Language.English]: {
    appName: 'Pixly',
    productPhoto: 'PRODUCT PHOTO',
    productPhotoSub: 'Product Photo and Main Photo',
    subjectType: 'SUBJECT TYPE',
    genderModel: 'MODEL GENDER',
    aiModel: 'OR SELECT AI MODEL',
    noModel: 'No Model',
    background: 'BACKGROUND',
    backgroundSub: 'Background Photo',
    additionalPrompt: 'ADDITIONAL PROMPT',
    additionalPromptPlaceholder: "Add specific details (e.g., 'Sunset at that time', 'beside the house')...",
    style: 'STYLE',
    count: 'COUNT',
    ratio: 'RATIO',
    resolution: 'RESOLUTION',
    branding: 'BRANDING',
    brandingLabel: 'Create Your Brand Watermark',
    generate: 'Generate Content',
    female: 'Female',
    male: 'Male',
    retro: 'Retro',
    softAesthetic: 'Soft Aesthetic',
    hd: 'HD',
    standard: 'Standard',
    loading: 'Processing your creative request...',
    processing: 'Generating Professional Result...',
    success: 'Successfully generated!',
    error: 'An error occurred. Please try again.',
  },
  [Language.Indonesian]: {
    appName: 'Pixly',
    productPhoto: 'FOTO PRODUK',
    productPhotoSub: 'Foto Produk dan Foto Utama',
    subjectType: 'TIPE SUBJEK',
    genderModel: 'GENDER MODEL',
    aiModel: 'ATAU PILIH MODEL AI',
    noModel: 'Tanpa Model',
    background: 'LATAR',
    backgroundSub: 'Foto Latar Belakang',
    additionalPrompt: 'PROMPT TAMBAHAN',
    additionalPromptPlaceholder: "Tambahkan detail Khusus (cth: 'Senja Kala Itu', 'di samping rumah')...",
    style: 'GAYA',
    count: 'JUMLAH',
    ratio: 'RASIO',
    resolution: 'RESOLUSI',
    branding: 'BRANDING',
    brandingLabel: 'Buat Watermark Brand Anda',
    generate: 'Proses Konten',
    female: 'Wanita',
    male: 'Pria',
    retro: 'Retro',
    softAesthetic: 'Estetik Lembut',
    hd: 'HD',
    standard: 'Standar',
    loading: 'Sedang memproses permintaan kreatif Anda...',
    processing: 'Menghasilkan Hasil Profesional...',
    success: 'Berhasil dibuat!',
    error: 'Terjadi kesalahan. Silakan coba lagi.',
  },
  [Language.Malaysian]: {
    appName: 'Pixly',
    productPhoto: 'GAMBAR PRODUK',
    productPhotoSub: 'Gambar Produk dan Gambar Utama',
    subjectType: 'JENIS SUBJEK',
    genderModel: 'GENDER MODEL',
    aiModel: 'ATAU PILIH MODEL AI',
    noModel: 'Tanpa Model',
    background: 'LATAR BELAKANG',
    backgroundSub: 'Gambar Latar Belakang',
    additionalPrompt: 'PROMPT TAMBAHAN',
    additionalPromptPlaceholder: "Tambah butiran khusus (cth: 'Senja Pada Waktu Itu', 'di tepi rumah')...",
    style: 'GAYA',
    count: 'BILANGAN',
    ratio: 'NISBAH',
    resolution: 'RESOLUSI',
    branding: 'PENJENAMAAN',
    brandingLabel: 'Bina Watermark Jenama Anda',
    generate: 'Proses Kandungan',
    female: 'Wanita',
    male: 'Lelaki',
    retro: 'Retro',
    softAesthetic: 'Estetik Lembut',
    hd: 'HD',
    standard: 'Standard',
    loading: 'Sedang memproses permintaan kreatif anda...',
    processing: 'Menjana Hasil Profesional...',
    success: 'Berjaya dijana!',
    error: 'Ralat berlaku. Sila cuba lagi.',
  },
};
