
import { GoogleGenAI } from "@google/genai";
import { AspectRatio, Style, SubjectType, Gender } from "../types";

export interface GenerateImageParams {
  productImageBase64: string | null;
  backgroundImageBase64: string | null;
  subjectType: SubjectType;
  gender: Gender;
  noModel: boolean;
  additionalPrompt: string;
  style: Style;
  aspectRatio: AspectRatio;
}

export const generateProfessionalContent = async (params: GenerateImageParams): Promise<string[]> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  const {
    productImageBase64,
    backgroundImageBase64,
    subjectType,
    gender,
    noModel,
    additionalPrompt,
    style,
    aspectRatio
  } = params;

  // Build high-quality prompt for affiliate marketing
  const promptParts = [
    "Professional high-quality product photography for affiliate marketing.",
    `Focus: ${subjectType}.`,
    !noModel ? `Model context: ${gender}.` : "No model shown, product focus.",
    `Style: ${style} aesthetic.`,
    additionalPrompt ? `Details: ${additionalPrompt}.` : "Clean minimalist layout.",
    "Remove any existing watermarks and ensure a seamless blend between product and environment.",
    "High resolution, professional lighting, photorealistic."
  ];

  const fullPrompt = promptParts.join(" ");

  const contents: any[] = [{ text: fullPrompt }];

  if (productImageBase64) {
    contents.push({
      inlineData: {
        data: productImageBase64.split(',')[1],
        mimeType: 'image/png'
      }
    });
  }

  if (backgroundImageBase64) {
    contents.push({
      inlineData: {
        data: backgroundImageBase64.split(',')[1],
        mimeType: 'image/png'
      }
    });
  }

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: { parts: contents },
      config: {
        imageConfig: {
          aspectRatio: aspectRatio as any,
        }
      }
    });

    const results: string[] = [];
    
    // Safety check for candidates
    if (response.candidates && response.candidates.length > 0) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          results.push(`data:image/png;base64,${part.inlineData.data}`);
        }
      }
    }

    if (results.length === 0) {
       throw new Error("No image was generated by the model.");
    }

    return results;
  } catch (error) {
    console.error("Gemini Generation Error:", error);
    throw error;
  }
};
